name: bus
description: Black Unicorn Source manager.
version: 1.0.0
homepage: https://github.com/iamtheblackunicorn/bus
environment:
  sdk: '>=2.12.1 <3.0.0'
dependencies:
  path: ^1.8.0
  termstyle: ^1.7.0
  clibu: ^1.4.0
