name: bus
description: Black Unicorn Source manager.
version: 1.0.0
homepage: https://github.com/iamtheblackunicorn/bus
environment:
  sdk: '>=2.8.1 <3.0.0'
dependencies:
  path: ^1.7.0
  termstyle: ^1.0.0
